[project]
name = "esmembed"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "bio>=1.7.1",
    "esm>=3.1.0",
    "fire>=0.7.0",
    "h5py>=3.12.1",
    "tqdm>=4.67.1",
]
